# Text Cleaning

In [19]:
sample_text = "Url https://youtube.com email abc3@gmail.com <h1>Removing Tags </h1>"
sample_text

'Url https://youtube.com email abc3@gmail.com <h1>Removing Tags </h1>'

In [20]:
import re
def text_clean(text):
  url = re.compile(r'https?://\S+|www\.\S+')
  text = url.sub('', text)

  email = re.compile(r'[A-Za-z0-9._%+-]+@[\w]+\.[\w]+')
  text = email.sub('', text)

  tags = re.compile(r'<.*?>')
  text = tags.sub('', text)
  return text
text_clean(sample_text)

'Url  email  Removing Tags '

# Unicode Normalization

In [21]:
data = 'How are you🙌, i am good 💝 what about you😊???'
data

'How are you🙌, i am good 💝 what about you😊???'

In [22]:
data.encode('utf-8')

b'How are you\xf0\x9f\x99\x8c, i am good \xf0\x9f\x92\x9d what about you\xf0\x9f\x98\x8a???'

# Remove Punctuation

In [28]:
import pandas as pd

data = {
    "ID": [1, 2, 3, 4, 5],
    "Review": [
        "Wow!!! This movie was AMAZING!!!  Totally loved it!!! #BestMovieEver!!!",
        "Ugh... what a waste of time???  Soooo boring!!!",
        "Hmm... it was okay-ish???  Not great, not bad... just \"meh\"!!!",
        "LOL!!! The acting was sooo bad!!!??? I can't even!!!  #Cringe",
        "Brilliant!!! Loved the story-line, characters & music!!! Must-watch!!!"
    ],
    "Sentiment": ["Positive", "Negative", "Neutral", "Negative", "Positive"]
}

df = pd.DataFrame(data)
df

   ID                                             Review Sentiment
0   1  Wow!!! This movie was AMAZING!!!  Totally love...  Positive
1   2    Ugh... what a waste of time???  Soooo boring!!!  Negative
2   3  Hmm... it was okay-ish???  Not great, not bad....   Neutral
3   4  LOL!!! The acting was sooo bad!!!??? I can't e...  Negative
4   5  Brilliant!!! Loved the story-line, characters ...  Positive

In [24]:
import string
exclude = string.punctuation

In [27]:
def remove_pun(text):
  return text.translate(str.maketrans(' ',' ', exclude))
df['Review'] = df['Review'].apply(remove_pun)
df

   ID                                             Review Sentiment
0   1  Wow This movie was AMAZING  Totally loved it B...  Positive
1   2             Ugh what a waste of time  Soooo boring  Negative
2   3     Hmm it was okayish  Not great not bad just meh   Neutral
3   4    LOL The acting was sooo bad I cant even  Cringe  Negative
4   5  Brilliant Loved the storyline characters  musi...  Positive

# Handling Emojis

In [34]:
import emoji
print(emoji.demojize('You are 🥶'))

You are :cold_face: