# Word2Vec

**word2vec** is a popular technique in natural language processing (NLP) for learning vector representations of words. It was introduced by Mikolov et al. in 2013 and has since become a fundamental tool for various NLP tasks.
**Why word2vec is better than td-idf?**
Word2Vec and TF-IDF are both popular techniques for representing text data, but they serve different purposes and have distinct advantages and disadvantages. Here are some reasons why Word2Vec is often considered better than TF-IDF:
1. **Contextual Understanding**: Word2Vec captures the context of words in a sentence, allowing it to understand the meaning of words based on their surrounding words. TF-IDF, on the other hand, only considers the frequency of words in a document and does not capture any contextual information.
2. **Semantic Relationships**: Word2Vec can capture semantic relationships between words, such as synonyms and analogies. For example, it can understand that "king" is to "queen" as "man" is to "woman". TF-IDF does not capture these relationships and treats each word as an independent entity.
3. **Dimensionality Reduction**: Word2Vec generates dense vector representations of words, which can be more efficient for machine learning models. TF-IDF produces sparse vectors, which can be high-dimensional and may require additional techniques for dimensionality reduction.
4. **Generalization**: Word2Vec can generalize better to unseen data because it learns the underlying structure of the language. TF-IDF is more specific to the training data and may not perform well on new, unseen documents.
5. **Performance**: In many NLP tasks, Word2Vec has been shown to outperform TF-IDF, especially in tasks that require understanding the meaning of words and their relationships. For example, in tasks like sentiment analysis, word similarity, and machine translation, Word2Vec often yields better results than TF-IDF.
Here is a simple example of how to use Word2Vec in Python using the Gensim library:

In [ ]:
import pandas as pd
import numpy as np
import gensim
import nltk
from gensim.models import Word2Vec

In [ ]:
df = pd.read_csv('/content/Twitter_Data.csv')
df.shape

(162980, 2)

In [ ]:
df.head(2)

                                          clean_text  category
0  when modi promised “minimum government maximum...      -1.0
1  talk all the nonsense and continue all the dra...       0.0

In [ ]:
Review_Text = df.clean_text.fillna('').apply(gensim.utils.simple_preprocess)
Review_Text.sample(10)

128656    [see, how, common, man, are, facing, problems,...
90143     [congratulation, modi, for, huge, croudnow, pe...
115476    [after, this, interview, game, set, and, match...
85003     [india, conducts, successful, antisatellite, m...
117528    [modi, drinks, bhang, and, entertaining, publics]
86137     [modi, might, excellent, leader, when, comes, ...
64065     [announced, that, india, had, become, the, th,...
4952      [wow, please, tell, new, social, life, okay, l...
158822    [offcourse, people, dont, want, hear, barking,...
35937     [pranam, sadgurui, personally, feel, that, you...
Name: clean_text, dtype: object

In [ ]:
model = Word2Vec(
    sentences=Review_Text,
    window=5,
    min_count=5,
    vector_size=200,
    sg=0
)

In [ ]:
model.build_vocab(Review_Text, progress_per=500)

WARNING:gensim.models.keyedvectors:sorting after vectors have been allocated is expensive & error-prone

In [ ]:
model.train(Review_Text, total_examples=model.corpus_count, epochs=model.epochs)

WARNING:gensim.models.word2vec:Effective 'alpha' higher than previous training cycles

(12954868, 16159840)

In [ ]:
model.wv.most_similar('nonsense')

[('notbut', 0.5060918927192688),
 ('rubbish', 0.4763321876525879),
 ('advent', 0.36943987011909485),
 ('statements', 0.354775995016098),
 ('attitude', 0.35402166843414307),
 ('idiot', 0.3521529734134674),
 ('stupidity', 0.3388568162918091),
 ('intellectuals', 0.3071358799934387),
 ('kin', 0.3069626986980438),
 ('bullshit', 0.30581924319267273)]

In [ ]:
#How often a word appeared during training
model.wv.get_vecattr("kin", "count")

np.int64(21)

In [ ]:
model.wv.most_similar(positive=["sir", "mam"], negative=["human"])

[('madam', 0.5857190489768982),
 ('bro', 0.4821206331253052),
 ('hello', 0.478392094373703),
 ('patra', 0.4514216482639313),
 ('confirm', 0.4441852569580078),
 ('jee', 0.43222373723983765),
 ('jii', 0.42319825291633606),
 ('dear', 0.41969993710517883),
 ('fan', 0.4141535460948944),
 ('honorable', 0.40620043873786926)]

In [ ]:
model.wv.most_similar(positive=["king", "woman"], negative=["man"])

[('refer', 0.5635432600975037),
 ('pandya', 0.5439621806144714),
 ('naqvi', 0.5190141201019287),
 ('notified', 0.5088946223258972),
 ('morarji', 0.5020686984062195),
 ('bolna', 0.501266360282898),
 ('inactive', 0.487495094537735),
 ('sterlite', 0.4837246835231781),
 ('shilpa', 0.48054543137550354),
 ('narendr', 0.47957971692085266)]