### Basics Text Preproessing Practice using Python

In [51]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.tokenize import sent_tokenize, word_tokenize

nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [15]:
df = pd.read_csv('/content/IMDB Dataset.csv')
df.head(3)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive

In [16]:
df.shape

(50000, 2)

In [23]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [18]:
df['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [20]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

# Text Preprocessing

In [63]:
# Removing HTML tags
def Remove_tags(text):
  tags = re.compile(r'<[^>]+>')
  text = tags.sub('', text)
  return text
Remove_tags(df['review'][1])

'A wonderful little production. The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [36]:
# Lowercasing
def Lowercasing(text):
  lower_text = text.lower()
  return lower_text
Lowercasing(df['review'][1])

'a wonderful little production. <br /><br />the filming technique is very unassuming- very old-time-bbc fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />the actors are extremely well chosen- michael sheen not only "has got all the polari" but he has all the voices down pat too! you can truly see the seamless editing guided by the references to williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. a masterful production about one of the great master\'s of comedy and his life. <br /><br />the realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. it plays on our knowledge and our senses, particularly with the scenes concerning orton and halliwell and the sets (particularly of their flat with halliwell\'s murals decorating every surface) are terribly well done.'

In [38]:
# Remove punctuation
def Remove_Punct(text):
  clean_text = re.compile(r'[^\w\s]')
  text = clean_text.sub('', text)
  return text
Remove_Punct(df['review'][1])

'A wonderful little production br br The filming technique is very unassuming very oldtimeBBC fashion and gives a comforting and sometimes discomforting sense of realism to the entire piece br br The actors are extremely well chosen Michael Sheen not only has got all the polari but he has all the voices down pat too You can truly see the seamless editing guided by the references to Williams diary entries not only is it well worth the watching but it is a terrificly written and performed piece A masterful production about one of the great masters of comedy and his life br br The realism really comes home with the little things the fantasy of the guard which rather than use the traditional dream techniques remains solid then disappears It plays on our knowledge and our senses particularly with the scenes concerning Orton and Halliwell and the sets particularly of their flat with Halliwells murals decorating every surface are terribly well done'

In [62]:
# Remove stopwords
nltk.download('stopwords')
stopword = stopwords.words('english')

def Remove_Stopwords(text):
  new_text = []

  for word in text.split():
    stopword = set(stopwords.words('english'))
    new_text.append(word)
  return " ".join(new_text)
Remove_Stopwords(df['review'][1])

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [49]:
# Tokenization
def tokenize(text):
  final_text = word_tokenize(text)
  return final_text
tokenize(df['review'][1])

['A',
 'wonderful',
 'little',
 'production',
 '.',
 '<',
 'br',
 '/',
 '>',
 '<',
 'br',
 '/',
 '>',
 'The',
 'filming',
 'technique',
 'is',
 'very',
 'unassuming-',
 'very',
 'old-time-BBC',
 'fashion',
 'and',
 'gives',
 'a',
 'comforting',
 ',',
 'and',
 'sometimes',
 'discomforting',
 ',',
 'sense',
 'of',
 'realism',
 'to',
 'the',
 'entire',
 'piece',
 '.',
 '<',
 'br',
 '/',
 '>',
 '<',
 'br',
 '/',
 '>',
 'The',
 'actors',
 'are',
 'extremely',
 'well',
 'chosen-',
 'Michael',
 'Sheen',
 'not',
 'only',
 '``',
 'has',
 'got',
 'all',
 'the',
 'polari',
 "''",
 'but',
 'he',
 'has',
 'all',
 'the',
 'voices',
 'down',
 'pat',
 'too',
 '!',
 'You',
 'can',
 'truly',
 'see',
 'the',
 'seamless',
 'editing',
 'guided',
 'by',
 'the',
 'references',
 'to',
 'Williams',
 "'",
 'diary',
 'entries',
 ',',
 'not',
 'only',
 'is',
 'it',
 'well',
 'worth',
 'the',
 'watching',
 'but',
 'it',
 'is',
 'a',
 'terrificly',
 'written',
 'and',
 'performed',
 'piece',
 '.',
 'A',
 'masterful',
 'production',
 'about',
 'one',
 'of',
 'the',
 'great',
 'master',
 "'s",
 'of',
 'comedy',
 'and',
 'his',
 'life',
 '.',
 '<',
 'br',
 '/',
 '>',
 '<',
 'br',
 '/',
 '>',
 'The',
 'realism',
 'really',
 'comes',
 'home',
 'with',
 'the',
 'little',
 'things',
 ':',
 'the',
 'fantasy',
 'of',
 'the',
 'guard',
 'which',
 ',',
 'rather',
 'than',
 'use',
 'the',
 'traditional',
 "'dream",
 "'",
 'techniques',
 'remains',
 'solid',
 'then',
 'disappears',
 '.',
 'It',
 'plays',
 'on',
 'our',
 'knowledge',
 'and',
 'our',
 'senses',
 ',',
 'particularly',
 'with',
 'the',
 'scenes',
 'concerning',
 'Orton',
 'and',
 'Halliwell',
 'and',
 'the',
 'sets',
 '(',
 'particularly',
 'of',
 'their',
 'flat',
 'with',
 'Halliwell',
 "'s",
 'murals',
 'decorating',
 'every',
 'surface',
 ')',
 'are',
 'terribly',
 'well',
 'done',
 '.']

In [53]:
# Stemming
ps = PorterStemmer()

def stem_word(text10):
  return ' '.join([ps.stem(word) for word in text10.split()])
stem_word(df['review'][0])

"one of the other review ha mention that after watch just 1 oz episod you'll be hooked. they are right, as thi is exactli what happen with me.<br /><br />the first thing that struck me about oz wa it brutal and unflinch scene of violence, which set in right from the word go. trust me, thi is not a show for the faint heart or timid. thi show pull no punch with regard to drugs, sex or violence. it is hardcore, in the classic use of the word.<br /><br />it is call oz as that is the nicknam given to the oswald maximum secur state penitentary. it focus mainli on emerald city, an experiment section of the prison where all the cell have glass front and face inwards, so privaci is not high on the agenda. em citi is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgi deal and shadi agreement are never far away.<br /><br />i would say the main appeal of the show is due to the fact that it goe where other show wouldn't dare. forget pretti pictur paint for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episod i ever saw struck me as so nasti it wa surreal, i couldn't say i wa readi for it, but as i watch more, i develop a tast for oz, and got accustom to the high level of graphic violence. not just violence, but injustic (crook guard who'll be sold out for a nickel, inmat who'll kill on order and get away with it, well mannered, middl class inmat be turn into prison bitch due to their lack of street skill or prison experience) watch oz, you may becom comfort with what is uncomfort viewing....that if you can get in touch with your darker side."

In [61]:
wnl = WordNetLemmatizer()
import nltk
nltk.download('averaged_perceptron_tagger_eng') # Download the missing resource
nltk.download('wordnet') # Download the missing wordnet resource
from nltk.corpus import wordnet
def lem(text):
    def get_wordnet_pos(tag):
        if tag.startswith('J'):
            return wordnet.ADJ
        elif tag.startswith('V'):
            return wordnet.VERB
        elif tag.startswith('N'):
            return wordnet.NOUN
        elif tag.startswith('R'):
            return wordnet.ADV
        else:
            return wordnet.NOUN

    words = nltk.word_tokenize(text)
    words = [word for word in words if word.isalnum()]
    pos_tags = nltk.pos_tag(words)

    lemmatized = [wnl.lemmatize(word, get_wordnet_pos(tag)) for word, tag in pos_tags]

    return " ".join(lemmatized)
lem(df['review'][2])

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

'I think this be a wonderful way to spend time on a too hot summer weekend sit in the air condition theater and watch a comedy The plot be simplistic but the dialogue be witty and the character be likable even the well bread suspect serial killer While some may be disappoint when they realize this be not Match Point 2 Risk Addiction I think it be proof that Woody Allen be still fully in control of the style many of u have grow to br br This be the most I laugh at one of Woody comedy in year dare I say a decade While I never be impress with Scarlet Johanson in this she manage to tone down her sexy image and jump right into a average but spirited young br br This may not be the crown jewel of his career but it be witty than Devil Wears Prada and more interesting than Superman a great comedy to go see with friend'

In [ ]:
port_stem = PorterStemmer()
def stemming(content):
    stemmed_content = re.sub('[^a-zA-Z]', ' ', content)
    stemmed_content = stemmed_content.lower()
    stemmed_content = stemmed_content.split()
    stemmed_content = [port_stem.stem(words) for words in stemmed_content if words not in stopwords.words('english')]
    stemmed_content = ' '.join(stemmed_content)
    return stemmed_content